# Site Settings
title: Paul Gavrikov
url: ''
baseurl: '' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6
# modified slightly
style: styles-6-pg

#Profile information
name: Paul Gavrikov
tagline: PhD Candidate Computer Vision
pic: profile.jpeg

#sidebar links
email: "paul.gavrikov@hs-offenburg.de"
linkedin: paul-gavrikov-60a4666a
github: paulgavrikov
twitter: "@paulgavrikov"
#Update all the sections by editing the files inside _data folder.

# Tracker add google id like UA-xxx here
#analytics: 

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
